import type { PropsWithChildren } from 'react'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import './globals.css'
import Providers from '@/components/providers'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '800'],
})

export const metadata: Metadata = {
  title: 'Ashkal',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en' className='dark'>
      <Providers>
        <body className={poppins.className}>{children}</body>
      </Providers>
    </html>
  )
}
