import type { PropsWithChildren } from 'react'
import type { Metadata } from 'next'
import { ClerkProvider } from '@clerk/nextjs'
import { Poppins } from 'next/font/google'
import ThemeProvider from '@/components/layout/theme-provider'
import './globals.css'

const poppins = Poppins({
  subsets: ['latin'],
  weight: ['400', '500', '600', '800'],
})

export const metadata: Metadata = {
  title: 'Ashkal',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang='en'>
      <ClerkProvider>
        <ThemeProvider attribute='class' defaultTheme='system' enableSystem>
          <body className={poppins.className}>{children}</body>
        </ThemeProvider>
      </ClerkProvider>
    </html>
  )
}
